version: 2
updates:
    - package-ecosystem: "docker"
      directory: "/.github/dockerfile-for-dependabot/"
      schedule:
          interval: "daily"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 100
    - package-ecosystem: "gomod"
      directory: "/"  # Adjust if go.mod is in a subdirectory
      schedule:
          interval: "daily"
      open-pull-requests-limit: 10