version: 2

builds:
  - main: ./cmd/esec/
    flags:
      - -trimpath
    ldflags: >
      -X main.version={{.Version}}
      -s
      -w
      -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
    goarch:
      - amd64
      - arm64
    # Reproducible builds
    mod_timestamp: "{{ .CommitTimestamp }}"

# Archive with reproducible timestamps
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

# SHA256 checksums
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Source archive for auditability
source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

# SBOM generation using syft
sboms:
  - artifacts: archive
  - id: source
    artifacts: source

# Cosign keyless signing (signs checksum file)
signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

nfpms:
  - id: goreleaser
    maintainer: "Mads Schou <oss@mscno.dev>"
    description: "esec is a small and opinionated library to make it easy to manage encrypted secrets using public key asymmetric elliptic curve encryption."
    license: "MIT"
    homepage: "https://github.com/mscno/esec"
    formats:
      - deb
