version: 2

builds:
    - main: ./cmd/esec/
      flags:
          - -trimpath
      ldflags:
          - -s -w -X main.VERSION={{.Version}} -extldflags "-static"
      env:
          - CGO_ENABLED=0
      goos:
          - darwin
          - freebsd
          - linux
          - windows
      goarch:
          - amd64
          - arm64

nfpms:
    - id: goreleaser
      maintainer: "mscno <mscno@.com>"
      description: "esec is a small and opinionated library to make it easy to manage encrypted secrets using public key asymmetric elliptic curve encryption."
      license: "MIT"
      homepage: "https://github.com/mscno/esec"
      formats:
          - deb